"""
Analysis of local observational entropies in the state 
rho = (1/5) (2 |00><00| + 3 |1+><1+|).

"""

## imports
import numpy as np
import matplotlib.pyplot as plt
import sys
import multipartite as mp

## set up output log
np.set_printoptions(linewidth=200)
if True:
  sys.stdout = open('LOex.out.txt','w')

## print output tag
print("--------------------------------------")
print("LOex.out.txt")
print("Output generated by LOex.py.")
print()
print("mp.__version__ = %s"%(mp.__version__))
print("--------------------------------------")
print()

## print docstring
print(__doc__)

